export const Symbols = [
  ["alpha", "α"],
  ["beta", "β"],
  ["gamma", "γ"],
  ["delta", "δ"],
  ["epsilon", "ε"],
  ["theta", "θ"],
  ["lambda", "λ"],
  ["mu", "μ"],
  ["pi", "π"],
  ["sigma", "σ"],
  ["phi", "φ"],
  ["omega", "ω"],
  ["degree", "°"],
  ["plusminus", "±"],
  ["times", "×"],
  ["divide", "÷"],
  ["neq", "≠"],
  ["leq", "≤"],
  ["geq", "≥"],
  ["approx", "≈"],
  ["infinity", "∞"],
  ["sqrt", "√"],
  ["copyright", "©"],
  ["registered", "®"],
  ["trademark", "™"],
];
